language: node_js

node_js:
    - stable

install:
    - npm install
    - npm install node-pre-gyp node-pre-gyp-github -g

script: node-pre-gyp install --build-from-source

deploy:
    provider: npm
    email: '$NPM_EMAIL'
    api_key: '$NPM_TOKEN'
    skip_cleanup: true
    on:
        tags: true
